[project.urls]
repository = "https://github.com/daniele-canavese/chroma"

[tool.poetry]
name = "chroma"
version = "0.3.0"
description = "Pretty printing for Python"
authors = ["Daniele Canavese"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
rich = "^13.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
